version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ..:/workspace:cached
    environment:
      - JAVA_OPTS=-Xmx512m -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2  # TLSプロトコルを明示的に指定
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5435:5432" # 外部ツールからは5435で接続
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tomcatdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
